### ISSUE TITLE
Training data structure

### ISSUE THREAD

**Issue by plinders** [vanvalenlab/deepcell-tf#106]
I've used older versions of deepcell-tf in the past with some degree of success to segment HeLa cells from brightfield images. Back then, the structure of the training data (2 features, cell edge and cell interior) for sampling was as follows:

```
HeLa
│
└───set1
│   │   feature_0.png
│   │   feature_1.png
│   │   phase.png
│   
└───set2
│   │   feature_0.png
│   │   feature_1.png
│   │   phase.png
...
```

I've understood from the source code that this structure has been updated. I've tried running the provided Jupyter Notebooks to get a feel of how the training data .npz files are constructed but as I don't have access to the original raw data, I cannot replicate this training data structure with my own data. What's the preferred structure of raw images/annotated images to properly generate training data?

**Comment by willgraf** [comment]
Great question!  We have indeed changed the directory structure and style
of training data.  Now, each raw image (phase.tif) will have 1
corresponding annotation file.  We no longer use cell edge as training
data and instead generate this data from a unique cell mask. Instead of
having cell boundary and cell interior as different label files, we just
use a single file with each cell uniquely labeled.

An example structure would look like this:

HeLa
│
└───set1

│   │
    └───annotated

│   │   │   feature.png

│   │
    └───raw

│ │ │ phase.png

│
└───set2

│   │
    └───annotated

│ │ │ feature.png

│   │
    └───raw

│   │   │   phase.png


(The *annotated* and *raw* directories can be defined in the
*make_training_data* function call, or can be ignored by passing in empty
strings as the *raw_dir *and *annotation_dir* parameters

Thanks,
willgraf

**Comment by plinders** [comment]
Excellent, it's now working as expected. Thanks!

**Comment by willgraf** [comment]
Great, glad it's working.  I will close this issue.
