### ISSUE TITLE
Allow a single pixel to have two labels

### ISSUE THREAD

**Issue by MekWarrior** [vanvalenlab/deepcell-tf#139]
A number of images contain cells that are out of the focal plane and overlap with cells in the focal plane. These "stacked" cells could be segmented and tracked if the data structure allowed for it.

**Comment by willgraf** [comment]
I'm not sure how we can account for this in the data.  Maybe we can label those pixels with another label (like -1) to indicate that we do not know which cell_ID this pixel belongs to.

I don't think there is a good way to encode 2 labels for a single pixel in our training data.

**Comment by willgraf** [comment]
After re-evaluating this comment and the state of the project, I believe the best way forward for your situation would be to add another class for this type of data, which is do-able with either acquiring new labeled data or by implementing a custom transform.

I believe the more general solution to this issue is to create another labeled dataset and create another model. This way you can use both models to get both of your predicted labels.  Perhaps you can also use multiple semantic heads in a PanOptic model?

---

I'm going to close this issue.  If this comes up again, the issue will be re-opened.
