### ISSUE TITLE
SiameseDataGenerator should be tolerant of poorly formatted input data

### ISSUE THREAD

**Issue by MekWarrior** [vanvalenlab/deepcell-tf#151]
The tracking data generator should log and throw a custom error when data is poorly/incorrectly formatted. Ideally, it should be fault tolerant. At minimum it should throw an exception and fail on purpose.

**Comment by willgraf** [comment]
I would like to close this issue as the `SiameseDataGenerator` already checks for:

- Parent cell is in the last frame
- All batches contain one cell
- Missing daughters information

I think that these validations are sufficient, even though they do not validate all of the daughter data. Because we do not do label validation for instance segmentation models, I do not see why we need to validate the lineage data here in the data generator.

I could see a use for this in `deepcell-tracking` though.

**Comment by willgraf** [comment]
I'm going to close this issue as the `SiameseDataGenerator` does do some validation, but full `.trk` or `lineage.json` validation should live in `deepcell-tracking`. This is now being tracked in vanvalenlab/deepcell-tracking#51.
