### ISSUE TITLE
memory issues during inference with large images

### ISSUE THREAD

**Issue by angelolab** [vanvalenlab/deepcell-tf#288]
I get an out of memory error when trying to pass a 2048x2048x2 image to a bn_feature_net_skip_2D network backbone using an n1-standard-8 CPU from google cloud. My current workaround is a for loop that runs over smaller overlapping crops of the image. 

Its a pretty minor inconvenience, but will likely continue as we image larger and larger regions. I'm not sure if the work you guys have been putting into the deployment/tf.serving stuff is the logical way to address this, or doing some checking prior to running makes more sense

**Comment by willgraf** [comment]
I think the tiling/patch-wise processing is the appropriate way to handle this, as we cannot handle arbitrarily large image sizes with a single model.  Currently, this functionality exists in the [`deepcell-toolbox`](https://github.com/vanvalenlab/deepcell-toolbox/blob/808f796cdc03baa7a9f99dee798829c0a00e7fe9/deepcell_toolbox/utils.py#L125).

I am currently working on implementing this with the kiosk. This issue should be solved soon.

**Comment by ngreenwald** [comment]
Hey Will, 
This issue is popping up again, now that I'm using the deep watershed network that has a fixed input size. 

The tile/until looks quite useful! We've implemented basically the exact same thing in the caliban_toolbox to crop/uncrop an image for annotations. It will likely make sense at some point in the future to make one core function that we can import across projects. 

For the near future it probably makes the most sense for me to just call these within the deep watershed notebook, correct?

**Comment by willgraf** [comment]
I've added the [tile/untile functions](https://github.com/vanvalenlab/deepcell-toolbox/blob/5b889b562a3342a0faa7d6e8062e8f26d946e877/deepcell_toolbox/utils.py#L125) to the pip-installable `deepcell-toolbox`, so I think that would be the easiest way to use it. (that's what the notebook is using, if it tiles anything).

I have a nearly finished implementation in a [branch of the redis consumer](https://github.com/vanvalenlab/kiosk-redis-consumer/blob/6aca80da35ed7b5ae3551c4dbe4fb338b35ae23f/redis_consumer/consumers/image_consumer.py#L271).

We should definitely work to integrate the two versions of this function together.

**Comment by ngreenwald** [comment]
Got it. The only conceptual difference between the two implementations is what to do with the leftover pixels at the end. 

Your version has the last crop go from the end of the image, resulting in variable amounts of overlap depending how many pixels remain. 

My [implementation](https://github.com/vanvalenlab/caliban-toolbox/blob/dedc0a62d1d93cf38f16696413b81237cfb4963a/deepcell_toolbox/pre_annotation/npz_preprocessing.py#L891) instead pads the image with zeros, so that the crop still overlaps the same amount.  

There's some other overhead code in there that does other stuff, but the meat is the crop_helper and compute_crop_indices functions. 

I have a slight preference towards the latter for labeling data, since it reduces instances of slightly different segmentation that only differ by a few pixels. We could add a flag that specifies what to do with end pixels?

**Comment by ngreenwald** [comment]
Tried out the deep watershed with the tile script, worked great. It's so fast!!!! 10x faster than the fully_conv network for inference.

**Comment by willgraf** [comment]
I think this issue is closed with the addition of the deep watershed models of fixed input size.
