### ISSUE TITLE
Harmonize semantic heads between fpn.py and panoptic.py

### ISSUE THREAD

**Issue by vanvalen** [vanvalenlab/deepcell-tf#363]
**Is your feature request related to a problem? Please describe.**
We currently have two different versions of semantic heads - one in fpn and panoptic nets. It would be nice to harmonize them so we only have one set.

**Describe the solution you'd like**
One set of semantic heads used across the code base.

**Comment by willgraf** [comment]
Just to make some headway on this:

`fpn.py` has 2 functions that are used by other modules:
- `__create_pyramid_features`: used by `RetinaNet`, `FPNet`, and `PanopticNet` models.
- `__create_semantic_head`: used by `RetinaNet` and `FPNet`.  (`panoptic.py` defines it's own function of the same name)

The `__create_semantic_head` difference are pretty big:
- Differing `semantic_upsample` functions in `panoptic.py` do not use `UpsampleLike`. Does `RetinaNet` need `UpsampleLike` or can it be converted as well?
- `semantic_prediction` has just been merged into the body of `__create_semantic_head`.
- In `fpn.py` it looks like `__create_semantic_head` does an upsample on every semantic feature and sums the output, while the `panopticnet.py` just uses the final pyramid feature.

I mention `FPNet` here because it exists in `fpn.py`, but I think it could probably be removed. I think it was just an early take on the `PanopticNets`.

---

The differences in `__create_semantic_head` are fairly significant.
