### ISSUE TITLE
Separate deepcell.applications into its own repository

### ISSUE THREAD

**Issue by vanvalen** [vanvalenlab/deepcell-tf#405]
**Is your feature request related to a problem? Please describe.**
If we separate deepcell.applications into its own repository, we could pin the version of deepcell it is dependent on, allowing it to be robust to library changes.

**Comment by willgraf** [comment]
While this issue was started (see vanvalenlab/deepcell-applications), I think that this is an unnecessary migration, as `deepcell` is now a pip package that can be installed in GPU and CPU environments.

I'm going to close this issue noting that an Application can be easily adapted into a workflow, using the vanvalenlab/deepcell-applications repository as an example.
