### ISSUE TITLE
Memory error using large images with application

### ISSUE THREAD

**Issue by ngreenwald** [vanvalenlab/deepcell-tf#538]
**Describe the bug**
The Mesmer application is OOMing when predicting on large images. Given that we tile the inputs to the model and batch process the data, my suspicion is that it's the pre or post processing that is causing the problem. Will need to investigate to determine which step in the application code is causing the error. 

**To Reproduce**
Run app.predict on 18000x21000 image

**Comment by oldridge** [comment]
Thank you so much for posting this, Noah! In case it is helpful, I've attached the error log I get when calling `app.predict()` from a Jupyter notebook run through the vanvalenlab/deepcell-tf:0.9.0-gpu docker container. The highest tier of hardware I have tried running this on is a g4dn.16xlarge AWS instance (64 vCPU, 256 GB RAM, 1x 16 GB NVIDIA T4 GPU)

[mesmer_app_predict_oom_error_log.txt](https://github.com/vanvalenlab/deepcell-tf/files/6918718/mesmer_app_predict_oom_error_log.txt)

**Comment by vanvalen** [comment]
This looks like an OOM that is happening on the GPU. This is likely because in the `predict_segmentation` method of the application, we call the 'predict' of the keras model class. This ends up packaging the data into a dataset object, which effectively loads all of them on to the GPU at once. This is in spite of specifying the batch size. The solution should be to manually feed batches of a specified size to 'predict' rather than calling it on the full array of tiles.

**Comment by ngreenwald** [comment]
Yup, confirmed that this is the issue. I was able to significantly increase image size by passing batches directly to predict. I'll open a PR to add this in.

**Comment by ngreenwald** [comment]
@oldridge can you check out https://github.com/vanvalenlab/deepcell-tf/tree/app_batching and confirm this resolves your issue?
