### ISSUE TITLE
how to load 100,000 npy images (without memory error) to train a deppcell model

### ISSUE THREAD

**Issue by EdwardZhao1991** [vanvalenlab/deepcell-tf#577]
Dear all,

Thanks for the awesome work.

I want to train a deepcell model on 100, 000 images. The image-groud truth pairs are as follows:
```
img_0.npy # float64, (512,512,2), two-channel images
gt_0.npy # uint32, (512,512,1), instance-level cell labels 
img_1.npy
gt_1.npy
...
img_100000.npy
gt_100000.npy
```
In the official tutorial, the image and ground truth are saved as one `npz` file.
https://deepcell.readthedocs.io/en/master/notebooks/Training-Segmentation.html#Prepare-for-training

However, I can not save all my training data as one npz file because the total memory is more than **100GB**.
Thus, the dataloader in the tutorial does not work for my dataset.

How should I load this large dataset to train the deepcell?

**Comment by ngreenwald** [comment]
Currently there's not a super easy way to load a dataset that large. 

I would recommend starting with a small random sample of the whole dataset (around 10k-20k cells). This will allow for much faster model training and parameter tweaking. Once you have settings that give good results, you can then scale up the amount of training data. It could be that you start to see a plateau in model performance as a function of dataset size before you run out of memory. 

However, if that's not the case, it would require some effort in order to support datasets that can't be contained in memory

**Comment by EdwardZhao1991** [comment]
Got it. Thanks for your help.
