### ISSUE TITLE
Installation fails when using pip because of appnope 0.0.7

### ISSUE THREAD

**Issue by FiReTiTi** [vanvalenlab/deepcell-tf#578]
**Describe the bug**
When trying to install deepcell using pip, it fails because of appnope 0.0.7

**To Reproduce**

    pip install deepcell

**Expected behavior**

    INFO: pip is looking at multiple versions of appnope to determine which version is compatible with other requirements. This could take a while.
   Collecting appnope
     Downloading appnope-0.1.0-py2.py3-none-any.whl (4.0 kB)
     Downloading appnope-0.0.7.tar.gz (2.3 kB)
   ERROR: File "setup.py" not found for legacy project appnope from https://files.pythonhosted.org/packages/d5/c8/3a9da27436ab1f8fa2ad7bd6aeccd3d5dc69ab5090214d988d8f26db148b/appnope-0.0.7.tar.gz#sha256=41c495961091fe4014f651688bd669d7557743838417923867c8752fd54536b5 (from ipykernel->jupyter<2,>=1.0.0->DeepCell).

**Desktop (please complete the following information):**
 - OS: macOS Monterey
 - Python 3.8

**Solution?**
I think that it could be fixed by adding _"appnope==0.1.2"_ in the requirements or during the installation
I tried a workaround by installing first appnope `pip install appnope==0.1.2 deepcell`, and it worked.

**Comment by msschwartz21** [comment]
I can't reproduce this error locally. I suspect that it is the result of other packages that you have installed in your environment. Please let me know if the issue continues in a clean environment.

**Comment by FiReTiTi** [comment]
I created a new python 3.8 environment using miniconda on MacOSX Monterey (most up to date).
This issue is consistent and I have to use the workaround/solution I described above.

**Comment by msschwartz21** [comment]
Ok thank you for clarifying. I was able to reproduce that error on a Mac. 

Currently our recommendation is to use deepcell in a [docker container](https://github.com/vanvalenlab/deepcell-tf#install-with-docker) so that we can create a consistent environment. Unfortunately, we can't test and support installations of deepcell on the range of possible operating systems that may be used.

Thank you for bringing the issue to our attention and offering a potential solution for other users.
